# Generated by Django 3.1.5 on 2021-03-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210324_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
